2017-12-24 16:50:17 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 16:50:17 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 16:50:44 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 16:50:44 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 16:50:44 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 16:57:22 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 16:57:22 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 16:57:48 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 16:57:48 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 16:57:48 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 17:01:01 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 17:01:01 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x7d3e8655, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 17:01:28 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 17:01:28 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x7d3e8655, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 17:01:28 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 17:01:54 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 17:01:54 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x46271dd6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner$1.run(AnalysisDataRunner.java:55)
	at com.transformer.mr.etl.AnalysisDataRunner$1.run(AnalysisDataRunner.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:51)
2017-12-24 17:02:21 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 17:02:21 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x46271dd6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner$1.run(AnalysisDataRunner.java:55)
	at com.transformer.mr.etl.AnalysisDataRunner$1.run(AnalysisDataRunner.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:51)
2017-12-24 17:02:21 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner$1.run(AnalysisDataRunner.java:55)
	at com.transformer.mr.etl.AnalysisDataRunner$1.run(AnalysisDataRunner.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:51)
2017-12-24 17:11:57 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 17:11:57 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x7d3e8655, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 17:12:23 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-24 17:12:23 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x7d3e8655, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-24 17:12:23 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner$2.run(AnalysisDataRunner.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1622)
	at com.transformer.mr.etl.AnalysisDataRunner.test2(AnalysisDataRunner.java:88)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 14:02:35 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-25 14:02:35 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 14:03:02 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-25 14:03:02 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 14:03:02 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 14:06:22 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-25 14:06:22 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 14:06:49 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-25 14:06:49 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 14:06:49 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 15:59:59 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-25 15:59:59 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:481)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:839)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:642)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:390)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:271)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:195)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:253)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 16:00:25 [ERROR] - org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper -RecoverableZooKeeper.java(276) -ZooKeeper exists failed after 4 attempts
  2017-12-25 16:00:25 [ERROR] - org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher -ZooKeeperWatcher.java(559) -catalogtracker-on-hconnection-0x6933b6c6, quorum=slave1:2181,master:2181,salve2:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
2017-12-25 16:00:25 [FATAL] - org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation -HConnectionManager.java(2476) -Unexpected exception during initialization, aborting
  org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:143)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:427)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:77)
	at org.apache.hadoop.hbase.catalog.CatalogTracker.start(CatalogTracker.java:199)
	at org.apache.hadoop.hbase.client.HBaseAdmin.startCatalogTracker(HBaseAdmin.java:262)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getCatalogTracker(HBaseAdmin.java:235)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:306)
	at com.transformer.mr.etl.AnalysisDataRunner.setHBaseOutputConfig(AnalysisDataRunner.java:267)
	at com.transformer.mr.etl.AnalysisDataRunner.run(AnalysisDataRunner.java:150)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at com.transformer.mr.etl.AnalysisDataRunner.test1(AnalysisDataRunner.java:71)
	at com.transformer.mr.etl.AnalysisDataRunner.main(AnalysisDataRunner.java:48)
